title: Libby Hemphill
description: "Director, <a href=\"http://www.icpsr.umich.edu/RCMD\">Research Center for Minority Data</a> at ICPSR<br>Associate Professor at <a href=\"http://www.si.umich.edu\">UMSI</a>"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
